version: '3.3'

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'l2_main'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
